[package]
name = "hyper-tiny-server"
version = "0.1.0"
authors = ["mohaila <mohaila@xubudesk27>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.10"
futures = "0.1.29"
